8.0 base amount to text
open-synergy/server-tools pull request #2
Opened 2016-10-11 04:21 UTC by mikevhe18

2016-10-11 04:34 UTC, andhit-r requested changes
Lihat reviews

2016-10-11 04:34 UTC, andhit-r commented on base_amount_to_text/__openerp__.py
> +	'website': 'https://opensynergy-indonesia.com',
Disejajarkan dengan baris lainnya

2016-10-11 04:34 UTC, andhit-r commented on base_amount_to_text/__openerp__.py
> +        'data/res_currency_data.xml',
demo, bukan data

2016-10-11 04:34 UTC, andhit-r commented on base_amount_to_text/models/res_currency.py
> +PYTHON_IDR = """result=''
Jangan diletakan disini

2016-10-11 04:34 UTC, andhit-r commented on base_amount_to_text/models/res_currency.py
> +    def amount_to_text(self, currency):
jangan lupa self.ensure_one()

2016-10-11 04:34 UTC, andhit-r commented on base_amount_to_text/models/res_currency.py
> +    def amount_to_text(self, currency):
Knapa ada parameter currency lagi? Kan currency bisa diakses melalui self

2016-10-11 04:34 UTC, andhit-r commented on base_amount_to_text/models/res_currency.py
> +    @api.multi
Ini buat ngetest doank kah?

2016-10-11 04:34 UTC, andhit-r commented on base_amount_to_text/models/res_currency.py
> +    @api.model
Jangan diletakan disini, buat data demo saja.

2016-10-11 04:34 UTC, andhit-r commented on base_amount_to_text/view/res_currency_view.xml
> +                    <field mode="tree" name="rate_ids" attrs="{'readonly':[('base','=',True)]}" position="replace">
Pakai xpath

2016-10-11 04:34 UTC, andhit-r commented on base_amount_to_text/view/res_currency_view.xml
> +                    <field mode="tree" name="rate_ids" attrs="{'readonly':[('base','=',True)]}" position="replace">
Kenapa inheritnya dari sini? Kenapa ga dari notebook saja?

2016-10-11 04:34 UTC, andhit-r commented on base_amount_to_text/view/res_currency_view.xml
> +<?xml version="1.0" encoding="utf-8"?>
Rapihkan indentasi

2016-10-11 04:38 UTC, mikevhe18 commented on base_amount_to_text/models/res_currency.py
> +PYTHON_IDR = """result=''
Ini ya mas, ini khan module masih RAW. Makanya tadi koordinasi dulu apakah sebaiknya pake demo atau data. Kalau memang pake demo ntar dihapus yang ini.

2016-10-11 04:42 UTC, andhit-r commented
Close to trigger travis

2016-10-11 04:42 UTC, mikevhe18 commented on base_amount_to_text/models/res_currency.py
> +    def amount_to_text(self, currency):
Ini parameter currency untuk masuk ke variabel di fungsi yang dibuat mas.

2016-10-11 04:43 UTC, mikevhe18 commented on base_amount_to_text/models/res_currency.py
> +    @api.multi
Iya ini fungsi tombol buat ngetest aja mas. Seperti yang tadi udah dibahas via telepon, baiknya dibikin satu fitur untuk ngetest apa ngga usah ?

2016-10-11 04:45 UTC, mikevhe18 commented on base_amount_to_text/view/res_currency_view.xml
> +                    <field mode="tree" name="rate_ids" attrs="{'readonly':[('base','=',True)]}" position="replace">
Ini masih hasil copy dari module terdahulu mas, belum diupdate. Nanti bakalan diupdate

2016-10-11 04:46 UTC, andhit-r commented on base_amount_to_text/models/res_currency.py
> +    @api.multi
Oke ini dibuang saja, tapi buat unittest

2016-10-11 12:33 UTC, andhit-r commented
@mikevhe18 travis msh merah

2016-10-12 04:56 UTC, mikevhe18 commented
@andhit-r mas, itu errornya ada dari module lain mas

2016-10-12 06:14 UTC, andhit-r commented on base_amount_to_text/models/res_currency.py
> +PYTHON_IDR = """result=''
Mike ini sepertinya ga perlu. Contoh sintaksnya lo masukin aja di unittest. Jadi ga perlu ada xml data tambahan

2016-10-14 00:01 UTC, andhit-r requested changes
Masih ada beberapa yang butuh revisi

2016-10-14 00:01 UTC, andhit-r commented on base_amount_to_text/view/res_lang_view.xml
> +        <record id="form_base_langAmntToText" model="ir.ui.view">
res_lang_view_form, coba baca lagi contrbuting.MD nya OCA

2016-10-14 00:01 UTC, andhit-r commented on base_amount_to_text/tests/test_amount2text.py
> +        result_1 = lang.amount_to_text(value_1) + 'Rupiah'
Ini rupiahnya ga bisa dimasukin dalam fungsi yah mike?

2016-10-14 12:32 UTC, mikevhe18 commented on base_amount_to_text/tests/test_amount2text.py
> +        result_1 = lang.amount_to_text(value_1) + 'Rupiah'
Ga bisa mas, soalnya buat test kedua yang pake sen, kalau misalnya rupiahnya ada di fungsi, hasilnya bakal keluar Rupiah 2x. Untuk yang ada sennya, fungsi terbilangnya kan dipanggil 2x.
Contoh : 1000000.50 (Satu Juta Rupiah Koma Lima Puluh Sen Rupiah)

2016-10-18 08:17 UTC, andhit-r requested changes

2016-10-18 08:17 UTC, andhit-r commented on base_amount_to_text/tests/test_amount2text.py
> +        data_languange = self._prepare_languange_IDR()
Mike coba buat amount to text untuk IDR tapi dalam en_US

2016-12-11 02:10 UTC, closed without merging